--- 
abstract: Method declaration with type checking
author: Anders Nor Berle <debolaz@gmail.com>
build_requires: 
  Test::Exception: 0.25
  Test::More: 0.70
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Method
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Moose: 0.20
  Scalar::Util: 1.19
  Sub::Name: 0.02
version: 0.22
