--- 
abstract: Method declaration with type checking
author: Anders Nor Berle <debolaz@gmail.com>
build_requires: 
  Test::Exception: 0.25
  Test::More: 0.70
  Test::Pod: 1.26
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-Method
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::MOP: 0.40
  Module::Find: 0.05
  Moose: 0.24
  Scalar::Util: 1.19
  Sub::Name: 0.02
version: 0.39
